version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://api-gateway:8002
    depends_on:
      - api-gateway

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8002:8002"
    environment:
      - STT_SERVICE_URL=http://stt-service:8000
      - SUMMARIZATION_SERVICE_URL=http://summarization-service:8001
    depends_on:
      - stt-service
      - summarization-service

  stt-service:
    build: ./backend/stt-service
    container_name: stt-service
    ports:
      - "8000:8000"
    environment:
      - MODEL_TYPE=base

  summarization-service:
    build: ./backend/summarization-service
    container_name: summarization-service
    ports:
      - "8001:8001"
    environment:
      - MODEL_TYPE=distilbart-cnn
