version: '3.7'
services:
  stt-service:
    image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/stt-service:latest
    ports:
      - "8000:8000"
    environment:
      - ENV=production

  summarization-service:
    image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/summarization-service:latest
    ports:
      - "8001:8001"
    environment:
      - ENV=production

  api-gateway:
    image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/api-gateway:latest
    ports:
      - "8002:8002"
    depends_on:
      - stt-service
      - summarization-service
    environment:
      - ENV=production
