apiVersion: v1
kind: Service
metadata:
  name: stt-service
spec:
  selector:
    app: stt-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: summarization-service
spec:
  selector:
    app: summarization-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
